### ISSUE TITLE
Integrate with Confluent schema registry (Avro)

### ISSUE THREAD

**Issue by azell** [infinimesh/kaf#38]
Would be nice to have a non-JVM alternative to kafka-avro-console-consumer

**Comment by birdayz** [comment]
can you elaborate what this would do for the CLI? e.g. displaying the avro payloads in JSON format?
i'm not actively using avro as our techstack uses mostly protobuf and JSON.

**Comment by azell** [comment]
Sure!  The goal would be to publish or consume Avro-encoded messages from the CLI using the Confluent schema registry for encoding or decoding.

Currently to do so from the command line requires having the Confluent stack installed along with the JVM.  There would be an additional CLI option required to point to the schema registry's endpoint as a Kafka property.

Example for kafka-avro-console-consumer:
```
--property schema.registry.url=https://confluent-registry.foo.bar
```

**Comment by birdayz** [comment]
okay so the console producer/consumer just reads/prints avro in JSON format, from what i read here: https://docs.confluent.io/1.0.1/quickstart.html

so this would entail fetching the schema from schema registry, and using an avro library to pretty convert to/from avro. could be interesting. i'd like to have the same for protobuf, but the tooling is rather difficult as there's no really good schema registry out there for proto.
